### PR TITLE
Fixed webapp!

### PR DESCRIPTION
**Pull request by Dummydud3**
Took me 2 weeks and a lot of googling.

### CODE REVIEW

**Comment by Brikwerk** [comment]
Thanks again for your interest in helping out with this project.

I believe this fix is mainly to do with the webapp getting stuck at the "Loading" stage, right? If so, would you mind explaining how this PR fixes the issue? This question mostly comes from my curiosity since I haven't been able to reproduce this bug.

Overall, I'm seeing a Flask-SocketIO version bump and an endpoint renaming in this PR. Did the version bump solve the webapp issues and then the endpoint renaming was necessary with the version bump?

**Comment by Dummydud3** [comment]
unfortunately theres a 95% chance that its actually my fault that it stopped working, because the older version of Socket wouldn't send any emits to the client. I also separated the webapp functions for easier debug.

**Comment by Dummydud3** [comment]
I did spend around 4 hours debuging the webapp, and i found that the server, `app.py` wasn't sending input to the client. So after a quick google, I just fixed it. I have a local installation with all the debugging code, so if you would like to see my results, feel free to let me know!

**Review by Brikwerk — APPROVED** [review]
Looks good. Thanks for the explanation.

**Pull request merged**
